version: "3.8"
networks: 
    network:
        driver: bridge
volumes:
    www-root:
    mysql-root:
services: 
    store:
        build: 
            context: ./alpine
            dockerfile: Dockerfile
        image: project:store
        hostname: store_server
        volumes:
            - www-root:/data/www-root
            #- mysql-root:/data/mysql-root
        networks:
            - network
    composer:
        build: 
            context: ./composer
            dockerfile: Dockerfile
        image: project:composer
        hostname: composer_server
        #command: ["top"]
        #entrypoint: ["top"]
        volumes:
            - ./composer/home:/tmp
            - ./www:/app
        networks:
            - network
    phpfpm:
        image: php:fpm
        hostname: php_server
        restart: always
        volumes:
            - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/php.ini-production:/usr/local/etc/php/php.ini
            - ./www:/var/www/html
        networks:
            - network
        depends_on: 
            - mysql
        links: 
            - mysql:mysql_server
    nginx:
        image: nginx
        hostname: nginx_server
        ports:
            - 8080:80
        volumes:
            - type: bind
              source: ./nginx/default.conf
              target: /etc/nginx/conf.d/default.conf
            - type: bind
              source: ./nginx/nginx.conf
              target: /etc/nginx/nginx.conf
            - type: bind
              source: ./www
              target: /usr/share/nginx/html
            #- type: volume
            #  source: www-root
            #  target: /usr/share/nginx/html
            #  volume:
            #    nocopy: true
            #  read_only: true
        networks:
            - network
        depends_on: 
            - phpfpm
        links: 
            - phpfpm:php_server
    mysql: 
        image: mysql
        hostname: mysql_server
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: drupal
            MYSQL_USER: drupal
            MYSQL_PASSWORD: drupal
        restart: always
        volumes:
            - mysql-root:/var/lib/mysql
        networks:
            - network